environments:
  production:
    database:
      name: caresync_production
      type: postgresql
      version: "14"
      initial_size: 10 # GB
      instance_class: db.t3.medium

    app:
      env:
        NODE_ENV: production
        PORT: "8080"
        DB_NAME: "${DATABASE_URL}"
        DB_USER: "${DATABASE_USER}"
        DB_PASSWORD: "${DATABASE_PASSWORD}"
        DB_HOST: "${DATABASE_HOST}"
        DB_PORT: "${DATABASE_PORT}"
      command: ["node", "server.js"]
      health_check:
        path: /health
        port: 8080
        protocol: http
        timeout: 15
        interval: 10
      expose:
        - 8080:8080

# Environment configuration
env:
  - VITE_API_URL
  - NODE_ENV=production
  - DB_USER
  - DB_HOST
  - DB_NAME
  - DB_PASSWORD
  - DB_PORT

# Database configuration
databases:
  - type: postgresql
    version: 14
    name: caresync_db 